//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сортировка
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Id_Inventory { get; set; }
        public string Number { get; set; }
        public System.DateTime Data_input { get; set; }
        public int Identifier { get; set; }
        public Nullable<int> NumberKab { get; set; }
    
        public virtual Identifier Identifier1 { get; set; }
        public virtual NumberKab NumberKab1 { get; set; }
    }
}
