//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сортировка
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SortEntities : DbContext
    {
        public SortEntities()
            : base("name=SortEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Identifier> Identifiers { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<NumberKab> NumberKabs { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
